language: python
group: travis_latest
dist: xenial

python:
- 3.8-dev
- 3.7
- 3.6.6

addons:
  apt:
    packages:
    - ffmpeg

install: pip install -e .

script:
- flake8
- mypy . --ignore-missing-imports
- pytest -v
